export const ROUTE_LOGIN_SCREEN = 'ROUTE_LOGIN_SCREEN';
export const ROUTE_SMS_SCREEN = 'ROUTE_SMS_SCREEN';
export const ROUTE_MAIN_SCREEN = 'ROUTE_MAIN_SCREEN';

export const LOG_IN = 'LOG_IN';
export const LOG_OUT = 'LOG_OUT';

export const SHOW_ORDERS_LIST = 'SHOW_ORDERS_LIST';
export const SHOW_ORDER_DETAIL = 'SHOW_ORDER_DETAIL';
export const CANCEL_ORDER = 'CANCEL_ORDER';
export const SHOW_ORDER_ROUTING = 'SHOW_ORDER_ROUTING';
export const GET_ORDER_PRICE = 'GET_ORDER_PRICE';
export const CREATE_ORDER = 'CREATE_ORDER';
export const UPDATE_ORDER = 'UPDATE_ORDER';